server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html #生成模板类型选择html
    enabled: true
    suffix: .ftl            #设置默认读取模板文件的后缀
    template-loader-path: classpath:/templates #模板文件所在的地址